#!/bin/bash

path=$(pwd)

echo -e "\ncurrent path: $path\n"

# CHECK FOR DEBUG
debugCheck=$(cd $path && svn diff | grep -i DEBUG)
if [ $? -eq 0 ]
then
	read -p "WARNING!!! Some DEBUG strings found in svn diff. Continue? (y/N): " yn
	yn=$(echo $yn | tr "[:upper:]" "[:lower:]")
	if [ "$yn" != "y" ]
	then
		exit 1
	fi
fi

# SVN ADD
num=$(cd $path && svn status | grep ^[!?] | wc -l)
if [ $num -gt 0 ]
then
	echo "you have $num svn untracked files"
	cd $path && svn status
	read -p "add this changes to svn? (Y/n): " yn
	yn=$(echo $yn | tr "[:upper:]" "[:lower:]")
	if [ "$yn" != "n" ]
	then
		cd $path && svn add --force .
	fi
fi

# SVN UPDATE
read -p "exec SVN update? (Y/n): " yn
yn=$(echo $yn | tr "[:upper:]" "[:lower:]")
if [ "$yn" != "n" ]
then
	cd $path && svn update
	if [ $? -eq 0 ]
	then
		echo -e "SVN UPDATED!\n"
	else
		echo "!!! ERROR !!!"
		echo "svn update failed with exitcode $?"
		exit 1
	fi
fi

# JS/CSS BUILDING
read -p "build JS & CSS? (Y/n): " yn
yn=$(echo $yn | tr "[:upper:]" "[:lower:]")
if [ "$yn" != "n" ]; then
	echo -e "\nJS/CSS BUILDING START!"
	cd ${path}/public/js/ && php build-production.php http://urlshortener.local
	# cd ${path}/public/js/ && sh ./js steal/buildjs http://urlshortener.local -to prod

	if [ $? -eq 0 ]
	then
		echo -e "JS BUILDING COMPLETE!\n"
	else
		echo "!!! ERROR !!!"
		echo "js building failed with exitcode $?"
		exit 1
	fi
fi

# SVN COMMIT
echo -e "\nSVN status"
cd $path && svn status
echo ""

read -p "SVN commit message: " svnCommitMsg;
cd $path && svn commit -m "$svnCommitMsg"
echo -e "SVN COMMITTED!\n"

read -p "REDMINE? "

echo ""
read -p "GOOGLE DOC? "

echo -e "\nFINISH!"
exit 0
