#!/bin/bash

# CHECK FOR DEBUG
debugCheck=$(cd /var/www/urlshortener/ && svn diff | grep -i DEBUG)
if [ $? -eq 0 ]
then
	read -p "WARNING!!! Some DEBUG strings found in svn diff. Continue? (y/N): " yn
	yn=$(echo $yn | tr "[:upper:]" "[:lower:]")
	if [ "$yn" != "y" ]
	then
		exit 1
	fi
fi

# SVN ADD
num=$(cd /var/www/urlshortener/ && svn status | grep ^[!?] | wc -l)
if [ $num -gt 0 ]
then
	echo "you have $num svn untracked files"
	cd /var/www/urlshortener/ && svn status
	read -p "add this changes to svn? (Y/n): " yn
	yn=$(echo $yn | tr "[:upper:]" "[:lower:]")
	if [ "$yn" != "n" ]
	then
		cd /var/www/urlshortener/ && svn add --force .
	fi
fi

# SVN UPDATE
read -p "exec SVN update? (Y/n): " yn
yn=$(echo $yn | tr "[:upper:]" "[:lower:]")
if [ "$yn" != "n" ]
then
	cd /var/www/urlshortener/ && svn update
	if [ $? -eq 0 ]
	then
		echo -e "SVN UPDATED!\n"
	else
		echo "!!! ERROR !!!"
		echo "svn update failed with exitcode $?"
		exit 1
	fi
fi

# JS/CSS BUILDING
echo -e "\nJS/CSS BUILDING START!"
cd /var/www/urlshortener/public/js/ && sh ./js steal/buildjs http://urlshortener.local -to prod
# echo 'js stub'

if [ $? -eq 0 ]
then
	echo -e "JS BUILDING COMPLETE!\n"
else
	echo "!!! ERROR !!!"
	echo "js building failed with exitcode $?"
	exit 1
fi

# SVN COMMIT
read -p "SVN commit message: " svnCommitMsg;
cd /var/www/urlshortener/ && svn commit -m "$svnCommitMsg"
echo -e "SVN COMMITTED!\n"

read -p "REDMINE? "

echo ""
read -p "GOOGLE DOC? "

echo -e "\nFINISH!"
exit 0
